In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import pylab as pl
import numpy as np
df = pd.read_csv('/content/drive/My Drive/Deep Blue/Data/Wardwise Data/CSV Data Files/AWard.csv', header = None)

In [0]:
df.head()

0     1            2  ...            4            5            6
0  01-2014  4340  189442.6588  ...  166627.2971  70470684.13  2016605.606
1  02-2014  4341  189603.7736  ...  166769.0082  70230002.77  2010666.796
2  03-2014  4341  189764.8884  ...  166910.7193  70591024.82  2022544.417
3  04-2014  4342  189926.0033  ...  167052.4304  70831706.18  2034422.037
4  05-2014  4342  190087.1181  ...  167194.1415  71313068.92  2046299.657

[5 rows x 7 columns]

In [0]:
cols = ['Year','Connections','TotalPop','Slum','NonSlum','Demand','Consumption']
df.columns = cols
df.shape

(60, 7)

In [0]:
from sklearn import preprocessing 
scale=df.iloc[:,1:7].values;
print(scale);
  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(1000, 1200))
x_after_min_max_scaler = min_max_scaler.fit_transform(scale) 
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler) 
print(x_after_min_max_scaler)

  
Standardisation = preprocessing.StandardScaler()   
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(scale) 
print ("\nAfter Standardisation : \n", x_after_Standardisation) 


[[4.34000000e+03 1.89442659e+05 2.28153617e+04 1.66627297e+05
  7.04706841e+07 2.01660561e+06]
 [4.34100000e+03 1.89603774e+05 2.28347654e+04 1.66769008e+05
  7.02300028e+07 2.01066680e+06]
 [4.34100000e+03 1.89764888e+05 2.28541691e+04 1.66910719e+05
  7.05910248e+07 2.02254442e+06]
 [4.34200000e+03 1.89926003e+05 2.28735728e+04 1.67052430e+05
  7.08317062e+07 2.03442204e+06]
 [4.34200000e+03 1.90087118e+05 2.28929766e+04 1.67194141e+05
  7.13130689e+07 2.04629966e+06]
 [4.34200000e+03 1.90248233e+05 2.29123803e+04 1.67335853e+05
  7.10723875e+07 2.04036085e+06]
 [4.34200000e+03 1.90409348e+05 2.29317840e+04 1.67477564e+05
  7.10699807e+07 2.02848323e+06]
 [4.34200000e+03 1.90570463e+05 2.29511877e+04 1.67619275e+05
  7.08292994e+07 2.01660561e+06]
 [4.34200000e+03 1.90731577e+05 2.29705915e+04 1.67760986e+05
  7.08052312e+07 2.00472799e+06]
 [4.34200000e+03 1.90892692e+05 2.29899952e+04 1.67902697e+05
  7.06848905e+07 2.01066680e+06]
 [4.34200000e+03 1.91053807e+05 2.30093989e+04 1.6

In [0]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
vif["features"] = df.columns

TypeError: ignored

In [0]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing 
scale=df.iloc[:,2:7].values;

  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(4000,5000))
x_after_min_max_scaler = min_max_scaler.fit_transform(scale) 
print(x_after_min_max_scaler)
i=0
for row in x_after_min_max_scaler :
    for elem in row:
        df.at[i,'TotalPop']=elem
        df.at[i,'Slum']=elem
        df.at[i,'NonSlum']=elem
        df.at[i,'Demand']=elem
        df.at[i,'Consumption']=elem
    i+=1   

[[4892.11406939 4892.11406939 4892.11406939 4892.11406939 4892.11406939]
 [4870.536884   4870.536884   4870.536884   4870.536884   4870.536884  ]
 [4913.69125842 4913.69125842 4913.69125842 4913.69125842 4913.69125842]
 [4956.84562921 4956.84562921 4956.84562921 4956.84562921 4956.84562921]
 [5000.         5000.         5000.         5000.         5000.        ]
 [4978.42281461 4978.42281461 4978.42281461 4978.42281461 4978.42281461]
 [4935.26844382 4935.26844382 4935.26844382 4935.26844382 4935.26844382]
 [4892.11406939 4892.11406939 4892.11406939 4892.11406939 4892.11406939]
 [4848.9596986  4848.9596986  4848.9596986  4848.9596986  4848.9596986 ]
 [4870.536884   4870.536884   4870.536884   4870.536884   4870.536884  ]
 [4827.38251321 4827.38251321 4827.38251321 4827.38251321 4827.38251321]
 [4978.42281461 4978.42281461 4978.42281461 4978.42281461 4978.42281461]
 [4837.64589046 4837.64589046 4837.64589046 4837.64589046 4837.64589046]
 [4859.22307585 4859.22307585 4859.22307585 4859.22

In [0]:
print(df)

       Year  Connections     TotalPop  ...      NonSlum       Demand  Consumption
0   01-2014         4340  4892.114069  ...  4892.114069  4892.114069  4892.114069
1   02-2014         4341  4870.536884  ...  4870.536884  4870.536884  4870.536884
2   03-2014         4341  4913.691258  ...  4913.691258  4913.691258  4913.691258
3   04-2014         4342  4956.845629  ...  4956.845629  4956.845629  4956.845629
4   05-2014         4342  5000.000000  ...  5000.000000  5000.000000  5000.000000
5   06-2014         4342  4978.422815  ...  4978.422815  4978.422815  4978.422815
6   07-2014         4342  4935.268444  ...  4935.268444  4935.268444  4935.268444
7   08-2014         4342  4892.114069  ...  4892.114069  4892.114069  4892.114069
8   09-2014         4342  4848.959699  ...  4848.959699  4848.959699  4848.959699
9   10-2014         4342  4870.536884  ...  4870.536884  4870.536884  4870.536884
10  11-2014         4342  4827.382513  ...  4827.382513  4827.382513  4827.382513
11  12-2014     